=== MyCATApache/Mycat-Server/src/main/resources/schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 -
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -
 -      http://www.apache.org/licenses/LICENSE-2.0
 -
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!ELEMENT mycat:schema (schema*,dataNode*,dataHost*)>
<!ATTLIST mycat:schema xmlns:mycat CDATA #FIXED "http://io.mycat/">

<!ELEMENT schema (table*)>
<!ATTLIST schema name NMTOKEN #REQUIRED>
<!ATTLIST schema checkSQLschema NMTOKEN #IMPLIED>
<!ATTLIST schema dataNode CDATA #IMPLIED>
<!ATTLIST schema sqlMaxLimit CDATA #IMPLIED>

<!ELEMENT table (property*,(childTable*))>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST table nameSuffix CDATA #IMPLIED>
<!ATTLIST table dataNode CDATA #REQUIRED>
<!ATTLIST table rule NMTOKEN #IMPLIED>
<!ATTLIST table ruleRequired NMTOKEN #IMPLIED>
<!ATTLIST table primaryKey NMTOKEN #IMPLIED>
<!ATTLIST table subTables CDATA #IMPLIED>
<!ATTLIST table autoIncrement NMTOKEN #IMPLIED>
<!ATTLIST table needAddLimit NMTOKEN #IMPLIED>
<!ATTLIST table type NMTOKEN #IMPLIED>


<!ELEMENT childTable (property*,(childTable*))>
<!ATTLIST childTable name NMTOKEN #REQUIRED>
<!ATTLIST childTable joinKey NMTOKEN #REQUIRED>
<!ATTLIST childTable parentKey NMTOKEN #REQUIRED>
<!ATTLIST childTable primaryKey NMTOKEN #IMPLIED>
<!ATTLIST childTable autoIncrement NMTOKEN #IMPLIED>


<!ELEMENT dataNode (property*)>
<!ATTLIST dataNode name CDATA #REQUIRED>
<!ATTLIST dataNode dataHost CDATA #REQUIRED>
<!ATTLIST dataNode database CDATA #REQUIRED>

<!ELEMENT dataHost (heartbeat,(connectionInitSql*),(writeHost+))>
<!ATTLIST dataHost
  balance CDATA #REQUIRED
  maxCon CDATA #REQUIRED
  minCon CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  balance CDATA #REQUIRED
  maxRetryCount CDATA #REQUIRED
  writeType CDATA #IMPLIED
  switchType  CDATA #IMPLIED
  slaveThreshold  CDATA #IMPLIED
  tempReadHostAvailable CDATA #IMPLIED
  dbType CDATA #REQUIRED
  filters CDATA #IMPLIED
  logTime CDATA #IMPLIED
    slaveIDs CDATA #IMPLIED
  dbDriver CDATA #REQUIRED>

<!ELEMENT writeHost (readHost)*>
<!ATTLIST writeHost
  url CDATA #REQUIRED
  host NMTOKEN #REQUIRED
  password CDATA #REQUIRED
  user CDATA #REQUIRED
  usingDecrypt CDATA #IMPLIED>

<!ELEMENT heartbeat (#PCDATA)>
<!ELEMENT connectionInitSql (#PCDATA)>
<!ELEMENT readHost (property*) >
<!ATTLIST readHost
  host NMTOKEN #REQUIRED
  url CDATA #REQUIRED
  password CDATA #REQUIRED
  user CDATA #REQUIRED
  weight CDATA #IMPLIED
  usingDecrypt CDATA #IMPLIED>

=== MyCATApache/Mycat-Server/src/main/resources/schema.xml
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/">

	<schema name="mycat" checkSQLschema="true" sqlMaxLimit="100">
		<table name="t_user" primaryKey="user_id" dataNode="dn$1-2" rule="rule1" />
        <table name="t_node" primaryKey="vid" autoIncrement="true" dataNode="dn$1-2" rule="rule1" />
		<table name="t_area" type="global" primaryKey="ID" dataNode="dn$1-2" />
        <table name="t_range_bydate" dataNode="dn$1-2" />

	</schema>

	<dataNode name="dn1" dataHost="jdbchost" database="mycat_node1" />
	<dataNode name="dn2" dataHost="jdbchost2" database="mycat_node1" />

	<dataHost name="jdbchost" maxCon="500" minCon="10" balance="1"
       writeType="0" dbType="mysql" dbDriver="native">
		<heartbeat>select 1</heartbeat>
		<writeHost host="readshard" url="121.40.121.133:3306" user="root" password="zaq1xsw2cde3">
		    <readHost host="readshard" url="116.236.223.115:3307" user="root" password="root"/>
		</writeHost>
        <!-- <writeHost host="master" url="116.236.223.116:3306" user="root" password="xrpension">
		   <readHost host="readmaster" url="116.236.223.115:3307" user="root" password="root"/>
		</writeHost> -->

	</dataHost>
	<!-- -->
	<dataHost name="jdbchost2" maxCon="500" minCon="10" balance="1"
       writeType="0" dbType="mysql" dbDriver="native">
		<heartbeat>select 1</heartbeat>
        <writeHost host="readshard" url="121.40.121.133:3306" user="root" password="zaq1xsw2cde3">
		    <readHost host="readshard" url="116.236.223.118:3306" user="dbcluster" password="xrpension!DBCluster"/>
		</writeHost>
		<!-- <writeHost host="shard" url="116.236.223.118:3306" user="dbcluster" password="xrpension!DBCluster">
		   <readHost host="readshard" url="121.40.121.133:3306" user="root" password="zaq1xsw2cde3"/>
		</writeHost> -->
        <!-- <writeHost host="master" url="116.236.223.115:3307" user="root" password="root">
		   <readHost host="readmaster" url="116.236.223.115:3307" user="root" password="root"/>
		</writeHost> -->
	</dataHost>

</mycat:schema>

=== MyCATApache/Mycat-Server/origin/master/src/test/resources/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/">

  <!-- schema定义 -->
  <schema name="dbtest">
    <table name="tb2" dataNode="dnTest2,dnTest3" rule="rule1" />
  </schema>

  <!-- 数据节点定义，数据节点由数据源和其他一些参数组织而成。 -->
  <dataNode name="dnTest1" dataHost="localhost1" database="db1" /> 
  <dataNode name="dnTest2" dataHost="localhost1" database="db2" />
  <dataNode name="dnTest3" dataHost="localhost1" database="db3" />
<dataHost name="localhost1" maxCon="500" minCon="10" balance="0"
		dbType="mysql" dbDriver="native" >
		<heartbeat>select user()</heartbeat>
		<!-- can have multi write hosts -->
		<writeHost host="hostM1" url="localhost:3306" user="root"
			password="123456">
			<!-- can have multi read hosts -->
			<!-- <readHost host="hostS1" url="localhost:3307" user="root" password="123456" 
				/> -->
		</writeHost>
	</dataHost>

 
</mycat:schema>

=== MyCATApache/Mycat-Server/src/test/resources/route/disRoute/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - Licensed under the Apache License, Version 2.0 (the "License"); 
	- you may not use this file except in compliance with the License. - You 
	may obtain a copy of the License at - - http://www.apache.org/licenses/LICENSE-2.0 
	- - Unless required by applicable law or agreed to in writing, software - 
	distributed under the License is distributed on an "AS IS" BASIS, - WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. - See the 
	License for the specific language governing permissions and - limitations 
	under the License. -->
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="cndb" checkSQLschema="true" >
		<table name="sqtestmonth" primaryKey="ID" dataNode="dn3,dn4" rule="sharding-by-id" />
	</schema>
	<dataNode name="dn4" dataHost="localhost1" database="db4" />
	<dataNode name="dn3" dataHost="localhost1" database="db4" />


	<dataHost name="localhost1" maxCon="500" minCon="10" balance="0"
		dbType="mysql" dbDriver="native">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="localhost:3307" user="root" password="123456">
		</writeHost>
	</dataHost>
</mycat:schema>

=== MyCATApache/Mycat-Server/src/test/resources/route/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - Licensed under the Apache License, Version 2.0 (the "License"); 
	- you may not use this file except in compliance with the License. - You 
	may obtain a copy of the License at - - http://www.apache.org/licenses/LICENSE-2.0 
	- - Unless required by applicable law or agreed to in writing, software - 
	distributed under the License is distributed on an "AS IS" BASIS, - WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. - See the 
	License for the specific language governing permissions and - limitations 
	under the License. -->
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="cndb" checkSQLschema="true" >
		<table name="offer" dataNode="offer_dn$0-127" rule="offerRule" />
		<table name="offer_detail" dataNode="detail_dn0,detail_dn$1-127"
			rule="offerDetailRule" ruleRequired="false" />
		<table name="offer_date" dataNode="detail_dn0,detail_dn$1-127"
			rule="dateRule" ruleRequired="false" />

		<table name="independent" dataNode="independent_dn$0-126,independent_dn127" />
	</schema>
	<schema name="dubbo" dataNode="dubbo_dn" />
    <schema name="dubbo2" dataNode="dn1" >
        <table name="company" type="global" dataNode="dn1,dn2,dn3" />
        <table name="goods" type="global" dataNode="dn1,dn2,dn3" />
            </schema>
	<schema name="ignoreSchemaTest" dataNode="cndb_dn" checkSQLschema="true"/>
	<schema name="config">
		<table name="offer" dataNode="offer_dn$0-127" rule="offerRule"
			ruleRequired="true" />
	</schema>
	<schema name="none_node_test">
		<table name="offer" dataNode="offer_dn$0-127" rule="offerRule"
			ruleRequired="true" />
	</schema>
	<schema name="solo1" dataNode="solo1" />

	<schema name="TESTDB"  sqlMaxLimit="100">
		<table name="travelrecord" dataNode="dn1,dn2,dn3" rule="auto-sharding-long" />
		<!-- global table is auto cloned to all defined data nodes ,so can join 
			with any table whose sharding node is in the same data node -->
		<table name="company" type="global" dataNode="dn1,dn2,dn3" />
		<table name="goods" type="global" dataNode="dn1,dn2,dn3" />
		<table name="notpartionTable"  dataNode="dn1" />
		<table name="area" primaryKey="ID" type="global" dataNode="dn1,dn2,dn3" />
		<table name="employee" primaryKey="id" dataNode="dn1,dn2"
			rule="sharding-by-intfile" />
		<table name="customer" dataNode="dn1,dn2" rule="auto-sharding-long2">
			<childTable name="orders" joinKey="customer_id" parentKey="id">
				<childTable name="order_items" joinKey="order_id"
					parentKey="id" />
			</childTable>
			<childTable name="customer_addr" joinKey="customer_id"
				parentKey="id" />
		</table>
		<table name="globalsn" primaryKey="ID" type="global" dataNode="dn1" />
        <table name="offer" primaryKey="id" dataNode="offer_dn$1-20"
               rule="auto-sharding-rang-mod" />

        <table name="offer1" primaryKey="id" dataNode="offer_dn$1-36"
               rule="rangeDateHash" />
	</schema>

    <schema name="mysqldb"  sqlMaxLimit="100">
        <table name="offer" dataNode="dn1,dn2" rule="auto-sharding-long2" />
		<table name="autoslot" dataNode="dn1,dn2" rule="crc32slot" />
        <table name="offer1" dataNode="dn1" />
    </schema>
    <schema name="oracledb"  sqlMaxLimit="100">
        <table name="offer" dataNode="d_oracle1,d_oracle2" rule="auto-sharding-long2" />
        <table name="offer1" dataNode="d_oracle1" />
    </schema>

	<schema name="db2db"  sqlMaxLimit="100">
		<table name="offer" dataNode="db2_1,db2_2" rule="auto-sharding-long2" />
		<table name="offer1" dataNode="db2_1" />
	</schema>


	<schema name="sqlserverdb"  sqlMaxLimit="100">
		<table name="offer" dataNode="sqlserver_1,sqlserver_2" rule="auto-sharding-long2" />
		<table name="offer1" dataNode="sqlserver_1" />
	</schema>


	<schema name="pgdb"  sqlMaxLimit="100">
		<table name="offer" dataNode="pg_1,pg_2" rule="auto-sharding-long2" />
		<table name="offer1" dataNode="pg_1" />
	</schema>
	
	<schema name="subQueries" sqlMaxLimit="100">
		<table name="table_0" dataNode="dn1,dn2" type="global"/><!-- 全局表    -->
		<table name="table_1" dataNode="dn1"/>          <!-- 非分片表 -->
		<table name="subtest1" dataNode="dn1,dn2" rule="mod-long" />
		<table name="subtest2" dataNode="dn1,dn2,dn3" rule="auto-sharding-long" />
		<table name="subtest3" dataNode="dn2,dn3" rule="mod-long" />
		<table name="subtest4" dataNode="dn1,dn2" rule="mod-long" />
	</schema>

	<dataNode name="dn1" dataHost="localhost1" database="db1" />
	<dataNode name="dn2" dataHost="localhost1" database="db2" />
	<dataNode name="dn3" dataHost="localhost1" database="db3" />
	<dataNode name="cndb_dn" dataHost="localhost1" database="db4" />
	<dataNode name="offer_dn$0-127" dataHost="localhost1" database="db1$0-127" />
	<dataNode name="detail_dn$0-127" dataHost="localhost1" database="db2$0-127" />
    <dataNode name="test_wild1$1-3" dataHost="localhost$1-3" database="db1" />
    <dataNode name="test_wild$1-6" dataHost="localhost$1-3" database="db1$1-2" />
	<dataNode name="independent_dn$0-127" dataHost="localhost1"
		database="db7_$0-127" />
	<dataNode name="dubbo_dn" dataHost="localhost1" database="db8" />
	<dataNode name="solo1" dataHost="localhost1" database="db9" />

    <dataNode name="d_oracle1" dataHost="oracle1" database="base" />
    <dataNode name="d_oracle2" dataHost="oracle2" database="bwg" />

	<dataNode name="db2_1" dataHost="db21" database="base" />
	<dataNode name="db2_2" dataHost="db22" database="test" />

	<dataNode name="sqlserver_1" dataHost="ms1" database="base" />
	<dataNode name="sqlserver_2" dataHost="ms2" database="test" />

	<dataNode name="pg_1" dataHost="pg1" database="base" />
	<dataNode name="pg_2" dataHost="pg2" database="test" />

	<dataHost name="localhost1" maxCon="500" minCon="10" balance="0"
		dbType="mysql" dbDriver="native">
		<heartbeat>select user()</heartbeat>
		<!-- can have multi write hosts -->
		<writeHost host="hostM1" url="localhost:3306" user="root"
			password="123456">
			<!-- can have multi read hosts -->
			<!-- <readHost host="hostS1" url="localhost:3307" user="root" password="123456" 
				/> -->
		</writeHost>
	</dataHost>
    <dataHost name="localhost2" maxCon="500" minCon="10" balance="0"
              dbType="mysql" dbDriver="native">
        <heartbeat>select user()</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM2" url="localhost:3306" user="root"
                   password="123456">
            <!-- can have multi read hosts -->
            <!-- <readHost host="hostS1" url="localhost:3307" user="root" password="123456"
                /> -->
        </writeHost>
    </dataHost>
    <dataHost name="localhost3" maxCon="500" minCon="10" balance="0"
              dbType="mysql" dbDriver="native">
        <heartbeat>select user()</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM3" url="localhost:3306" user="root"
                   password="123456">
            <!-- can have multi read hosts -->
            <!-- <readHost host="hostS1" url="localhost:3307" user="root" password="123456"
                /> -->
        </writeHost>
    </dataHost>


    <dataHost name="oracle1" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <connectionInitSql>alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'</connectionInitSql>
        <writeHost host="ohostM1" url="jdbc:oracle:thin:@127.0.0.1:1521:nange" user="base" password="123456" >
        </writeHost>
    </dataHost>

    <dataHost name="oracle2" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="oracle" dbDriver="jdbc">
        <heartbeat>select 1 from dual</heartbeat>
        <connectionInitSql>alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'</connectionInitSql>
        <writeHost host="ohostM2" url="jdbc:oracle:thin:@127.0.0.1:1521:nange" user="bwg" password="123456" >
        </writeHost>
    </dataHost>


	<dataHost name="db21" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="db2" dbDriver="jdbc">
		<heartbeat>select 1 from SYSIBM.SYSDUMMY1</heartbeat>
		<writeHost host="dhostM1" url="jdbc:db2://127.0.0.1:50000/base" user="db2inst1" password="123" >
		</writeHost>
	</dataHost>


	<dataHost name="db22" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="db2" dbDriver="jdbc">
		<heartbeat>select 1 from SYSIBM.SYSDUMMY1</heartbeat>
		<writeHost host="dhostM2" url="jdbc:db2://127.0.0.1:50000/test" user="db2inst1" password="123" >
		</writeHost>
	</dataHost>



	<dataHost name="ms1" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="sqlserver" dbDriver="jdbc">
		<heartbeat>select 1 </heartbeat>
		<writeHost host="mhostM1" url="jdbc:sqlserver://127.0.0.1:1433;DatabaseName=base" user="base" password="123" >
		</writeHost>
	</dataHost>

	<dataHost name="ms2" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="sqlserver" dbDriver="jdbc">
		<heartbeat>select 1 </heartbeat>
		<writeHost host="mhostM2" url="jdbc:sqlserver://127.0.0.1:1433;DatabaseName=test" user="base" password="123" >
		</writeHost>
	</dataHost>
	<dataHost name="pg1" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="postgresql" dbDriver="jdbc">
		<heartbeat>select 1</heartbeat>
		<writeHost host="phostM1" url="jdbc:postgresql://127.0.0.1:5432/base" user="test" password="123" >
		</writeHost>
	</dataHost>

	<dataHost name="pg2" maxCon="1000" minCon="1" balance="0" writeType="0" dbType="postgresql" dbDriver="jdbc">
		<heartbeat>select 1 </heartbeat>
		<writeHost host="phostM2" url="jdbc:postgresql://127.0.0.1:5432/test" user="test" password="123" >
		</writeHost>
	</dataHost>

</mycat:schema>

=== MyCATApache/Mycat-Server/src/main/resources/zkconf/schema.xml
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

	<schema name="TESTDB" checkSQLschema="false" sqlMaxLimit="100">
		<!-- auto sharding by id (long) -->
		<table name="travelrecord" dataNode="dn1,dn2,dn3" rule="auto-sharding-long" />

		<!-- global table is auto cloned to all defined data nodes ,so can join
			with any table whose sharding node is in the same data node -->
		<table name="company" primaryKey="ID" type="global" dataNode="dn1,dn2,dn3" />
		<table name="goods" primaryKey="ID" type="global" dataNode="dn1,dn2" />
		<!-- random sharding using mod sharind rule -->
		<table name="hotnews" primaryKey="ID" autoIncrement="true" dataNode="dn1,dn2,dn3"
			   rule="mod-long" />
		<!-- <table name="dual" primaryKey="ID" dataNode="dnx,dnoracle2" type="global"
			needAddLimit="false"/> <table name="worker" primaryKey="ID" dataNode="jdbc_dn1,jdbc_dn2,jdbc_dn3"
			rule="mod-long" /> -->
		<table name="employee" primaryKey="ID" dataNode="dn1,dn2"
			   rule="sharding-by-intfile" />
		<table name="customer" primaryKey="ID" dataNode="dn1,dn2"
			   rule="sharding-by-intfile">
			<childTable name="orders" primaryKey="ID" joinKey="customer_id"
						parentKey="id">
				<childTable name="order_items" joinKey="order_id"
							parentKey="id" />
			</childTable>
			<childTable name="customer_addr" primaryKey="ID" joinKey="customer_id"
						parentKey="id" />
		</table>
		<!-- <table name="oc_call" primaryKey="ID" dataNode="dn1$0-743" rule="latest-month-calldate"
			/> -->
	</schema>
	<!-- <dataNode name="dn1$0-743" dataHost="localhost1" database="db$0-743"
		/> -->
	<dataNode name="dn1" dataHost="localhost1" database="db1" />
	<dataNode name="dn2" dataHost="localhost1" database="db2" />
	<dataNode name="dn3" dataHost="localhost1" database="db3" />
	<!--<dataNode name="dn4" dataHost="sequoiadb1" database="SAMPLE" />
	 <dataNode name="jdbc_dn1" dataHost="jdbchost" database="db1" />
	<dataNode	name="jdbc_dn2" dataHost="jdbchost" database="db2" />
	<dataNode name="jdbc_dn3" 	dataHost="jdbchost" database="db3" /> -->
	<dataHost name="localhost1" maxCon="1000" minCon="10" balance="0"
			  writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<!-- can have multi write hosts -->
		<writeHost host="hostM1" url="localhost:3306" user="root"
				   password="123456">
			<!-- can have multi read hosts -->
			<readHost host="hostS2" url="192.168.1.200:3306" user="root" password="xxx" />
		</writeHost>
		<writeHost host="hostS1" url="localhost:3316" user="root"
				   password="123456" />
		<!-- <writeHost host="hostM2" url="localhost:3316" user="root" password="123456"/> -->
	</dataHost>
	<!--
		<dataHost name="sequoiadb1" maxCon="1000" minCon="1" balance="0" dbType="sequoiadb" dbDriver="jdbc">
		<heartbeat> 		</heartbeat>
		 <writeHost host="hostM1" url="sequoiadb://1426587161.dbaas.sequoialab.net:11920/SAMPLE" user="jifeng" 	password="jifeng"></writeHost>
		 </dataHost>

	  <dataHost name="oracle1" maxCon="1000" minCon="1" balance="0" writeType="0" 	dbType="oracle" dbDriver="jdbc"> <heartbeat>select 1 from dual</heartbeat>
		<connectionInitSql>alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'</connectionInitSql>
		<writeHost host="hostM1" url="jdbc:oracle:thin:@127.0.0.1:1521:nange" user="base" 	password="123456" > </writeHost> </dataHost>

		<dataHost name="jdbchost" maxCon="1000" 	minCon="1" balance="0" writeType="0" dbType="mongodb" dbDriver="jdbc">
		<heartbeat>select 	user()</heartbeat>
		<writeHost host="hostM" url="mongodb://192.168.0.99/test" user="admin" password="123456" ></writeHost> </dataHost>

		<dataHost name="sparksql" maxCon="1000" minCon="1" balance="0" dbType="spark" dbDriver="jdbc">
		<heartbeat> </heartbeat>
		 <writeHost host="hostM1" url="jdbc:hive2://feng01:10000" user="jifeng" 	password="jifeng"></writeHost> </dataHost> -->

	<!-- <dataHost name="jdbchost" maxCon="1000" minCon="10" balance="0" dbType="mysql"
		dbDriver="jdbc"> <heartbeat>select user()</heartbeat> <writeHost host="hostM1"
		url="jdbc:mysql://localhost:3306" user="root" password="123456"> </writeHost>
		</dataHost> -->
</mycat:schema>

=== MyCATApache/Mycat-Server/src/test/resources/schema.xml
<?xml version="1.0"?>
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://org.opencloudb/">
    <schema name="user" checkSQLschema="false" sqlMaxLimit="100" dataNode="user" />
    <schema name="pay"  checkSQLschema="false" sqlMaxLimit="100" dataNode="pay" />

    <dataNode name="user" dataHost="host" database="user" />
    <dataNode name="pay" dataHost="host" database="pay" />

    <dataHost name="host" maxCon="1000" minCon="10" balance="0"
       writeType="0" dbType="mysql" dbDriver="native">
       <heartbeat>select 1</heartbeat>
       <!-- can have multi write hosts -->
       <writeHost host="hostM1" url="192.168.0.2:3306" user="root" password="root" />
       <writeHost host="hostM2" url="192.168.0.3:3306" user="root" password="root" />
    </dataHost>
</mycat:schema>

=== MyCATApache/Mycat-Server/build/resources/test/config/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE mycat:schema SYSTEM "schema.dtd">
<mycat:schema xmlns:mycat="http://io.mycat/">

  <!-- schema定义 -->
  <schema name="dbtest">
    <table name="tb2" dataNode="dnTest2,dnTest3" rule="rule1" />
  </schema>
  
  <schema name="dbtest1">    
   	<!-- 动态日期表设置, 格式： yyyymm,年,月,往后月数 -->
	<!-- 动态日期表设置, 格式： yyyymmdd,年,月,日,wanghou天数 -->
	<table name="dynamic_" nameSuffix="yyyymmdd,2015,08,01,15" dataNode="dnTest2,dnTest3" />
	<table name="dynamic_" nameSuffix="yyyymm,2015,01,15" dataNode="dnTest2,dnTest3" />
  </schema>
  
  <schema name="dbtest2" checkSQLschema="false" sqlMaxLimit="100" dataNode="dnTest4"></schema>


  <!-- 数据节点定义，数据节点由数据源和其他一些参数组织而成。 -->
  <dataNode name="dnTest1" dataHost="localhost1" database="db1" /> 
  <dataNode name="dnTest2" dataHost="localhost1" database="db2" />
  <dataNode name="dnTest3" dataHost="localhost1" database="db3" />
  <dataNode name="dnTest4" dataHost="localhost2" database="db4" />
  
  <dataHost name="localhost1" maxCon="500" minCon="10" balance="0"
		dbType="mysql" dbDriver="native" >
		<heartbeat>select user()</heartbeat>
		<!-- can have multi write hosts -->
		<writeHost host="hostM1" url="localhost:3306" user="root"
			password="123456">
			<!-- can have multi read hosts -->
			<!-- <readHost host="hostS1" url="localhost:3307" user="root" password="123456" 
				/> -->
		</writeHost>
	</dataHost>


	<!-- 读权重设置 -->
	<dataHost name="localhost2" maxCon="1000" minCon="10" balance="0"
		writeType="0" dbType="mysql" dbDriver="native" switchType="1"  slaveThreshold="100" tempReadHostAvailable="1">
		<heartbeat>select user()</heartbeat>		
		<writeHost host="writeS" url="192.168.1.10:3306" user="root" password="123456" >
			<!-- can have multi read hosts -->
			<readHost host="readS1" url="192.168.1.11:3306" user="root" password="123456" weight="1" />
			<readHost host="readS2" url="192.168.1.12:3306" user="root" password="123456" weight="2"/>
			<readHost host="readS3" url="192.168.1.13:3306" user="root" password="123456" weight="3"/>
		</writeHost>		
	</dataHost>
 
</mycat:schema>
