=== MyCATApache/Mycat-Server/build/resources/main/rule.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!ELEMENT mycat:rule (tableRule*,function*)>
<!ATTLIST mycat:rule xmlns:mycat CDATA #FIXED "http://io.mycat/">

<!ELEMENT tableRule (rule+)>
<!ATTLIST tableRule name CDATA #REQUIRED>

<!ELEMENT rule (columns,algorithm)>
<!ELEMENT columns (#PCDATA)>
<!ELEMENT algorithm (#PCDATA)>

<!ELEMENT function (property*)>
<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST function class CDATA #REQUIRED>

<!ELEMENT property (#PCDATA | bean)*>
<!ATTLIST property name NMTOKEN #REQUIRED>

<!ELEMENT bean (property*)>
<!ATTLIST bean name NMTOKEN #IMPLIED>
<!ATTLIST bean class NMTOKEN #IMPLIED>

=== MyCATApache/Mycat-Server/origin/master/src/test/resources/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 -  
 - Licensed under the Apache License, Version 2.0 (the "License");
 - you may not use this file except in compliance with the License.
 - You may obtain a copy of the License at
 -  
 -      http://www.apache.org/licenses/LICENSE-2.0
 -  
 - Unless required by applicable law or agreed to in writing, software
 - distributed under the License is distributed on an "AS IS" BASIS,
 - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 - See the License for the specific language governing permissions and
 - limitations under the License.
-->
<!DOCTYPE mycat:rule SYSTEM "rule.dtd">
<mycat:rule xmlns:mycat="http://org.opencloudb/">

  <!-- 路由规则定义，定义什么表，什么字段，采用什么路由算法 -->
  <tableRule name="rule1">
    <rule>
      <columns>id</columns>
      <algorithm>func1</algorithm>
    </rule>
  </tableRule>

  <!-- 路由函数定义 -->
  <function name="func1"
    class="org.opencloudb.route.function.PartitionByLong">
    <property name="partitionCount">2</property>
    <property name="partitionLength">512</property>
  </function>

</mycat:rule>

=== MyCATApache/Mycat-Server/src/main/resources/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - Licensed under the Apache License, Version 2.0 (the "License"); 
	- you may not use this file except in compliance with the License. - You 
	may obtain a copy of the License at - - http://www.apache.org/licenses/LICENSE-2.0 
	- - Unless required by applicable law or agreed to in writing, software - 
	distributed under the License is distributed on an "AS IS" BASIS, - WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. - See the 
	License for the specific language governing permissions and - limitations 
	under the License. -->
<!DOCTYPE mycat:rule SYSTEM "rule.dtd">
<mycat:rule xmlns:mycat="http://io.mycat/">
	<!--固定分片hash算法-->
	<tableRule name="rule1">
		<rule>
			<columns>id</columns>
			<algorithm>func1</algorithm>
		</rule>
	</tableRule>

	<tableRule name="rule2">
		<rule>
			<columns>user_id</columns>
			<algorithm>func1</algorithm>
		</rule>
	</tableRule>

	<!--分片枚举-->
	<tableRule name="sharding-by-intfile">
		<rule>
			<columns>accounting_date</columns>
			<algorithm>hash-int</algorithm>
		</rule>
	</tableRule>

	<!--范围分片算法-->
	<tableRule name="auto-sharding-long">
		<rule>
			<columns>id</columns>
			<algorithm>rang-long</algorithm>
		</rule>
	</tableRule>

	<!--十进制取模算法-->
	<tableRule name="mod-long">
		<rule>
			<columns>id</columns>
			<algorithm>mod-long</algorithm>
		</rule>
	</tableRule>

	<!--一致性hash算法：主要解决分布式数据库扩容问题-->
	<tableRule name="sharding-by-murmur">
		<rule>
			<columns>id</columns>
			<algorithm>murmur</algorithm>
		</rule>
	</tableRule>

	<tableRule name="crc32slot">
		<rule>
			<columns>id</columns>
			<algorithm>crc32slot</algorithm>
		</rule>
	</tableRule>

	<!--根据日期来分片-->
	<tableRule name="dateRule">
		<rule>
			<columns>create_date</columns>
			<algorithm>by-date</algorithm>
		</rule>
	</tableRule>

	<!--按照月份分片-->
	<tableRule name="sharding-by-month">
		<rule>
			<columns>ACCOUNTING_DATE</columns>
			<algorithm>partbymonth</algorithm>
		</rule>
	</tableRule>

	<tableRule name="latest-month-calldate">
		<rule>
			<columns>calldate</columns>
			<algorithm>latestMonth</algorithm>
		</rule>
	</tableRule>

	<!--范围求模分片：分组内求模保证组内的数据均匀，分片组之间是范围分片可以兼顾范围查询-->
	<tableRule name="auto-sharding-rang-mod">
		<rule>
			<columns>id</columns>
			<algorithm>rang-mod</algorithm>
		</rule>
	</tableRule>
	
	<tableRule name="jch">
		<rule>
			<columns>id</columns>
			<algorithm>jump-consistent-hash</algorithm>
		</rule>
	</tableRule>

	<function name="by-date"
			  class="io.mycat.route.function.PartitionByDate">
		<!--日期只能从2018年的1月开始-->
		<property name="sBeginDate">2018-01-01</property>
		<!--以1天来拆分到不同的分片-->
		<property name="sPartionDay">1</property>
		<!--日期格式-->
		<property name="dateFormat">yyyy-MM-dd</property>
	</function>

	<!--一致性hash算法-->
	<function name="murmur"
		class="io.mycat.route.function.PartitionByMurmurHash">
		<property name="seed">0</property><!-- 默认是0 -->
		<property name="count">2</property><!-- 要分片的数据库节点数量，必须指定，否则没法分片 -->
		<property name="virtualBucketTimes">160</property><!-- 一个实际的数据库节点被映射为这么多虚拟节点，默认是160倍，也就是虚拟节点数是物理节点数的160倍 -->
		<!-- <property name="weightMapFile">weightMapFile</property> 节点的权重，没有指定权重的节点默认是1。以properties文件的格式填写，以从0开始到count-1的整数值也就是节点索引为key，以节点权重值为值。所有权重值必须是正整数，否则以1代替 -->
		<!-- <property name="bucketMapPath">/etc/mycat/bucketMapPath</property> 
			用于测试时观察各物理节点与虚拟节点的分布情况，如果指定了这个属性，会把虚拟节点的murmur hash值与物理节点的映射按行输出到这个文件，没有默认值，如果不指定，就不会输出任何东西 -->
	</function>

	<function name="crc32slot"
			  class="io.mycat.route.function.PartitionByCRC32PreSlot">
	</function>

	<function name="hash-int" class="io.mycat.route.function.PartitionByFileMap">
		<property name="mapFile">partition-hash-int.txt</property>
		<property name="type">1</property>
	</function>

	<function name="rang-long"
		class="io.mycat.route.function.AutoPartitionByLong">
		<property name="mapFile">autopartition-long.txt</property>
	</function>

	<function name="mod-long" class="io.mycat.route.function.PartitionByMod">
		<!-- 配置多少个数据节点 -->
		<property name="count">3</property>
	</function>

	<function name="func1" class="io.mycat.route.function.PartitionByLong">
		<property name="partitionCount">8</property>
		<property name="partitionLength">128</property>
	</function>

	<function name="latestMonth"
		class="io.mycat.route.function.LatestMonthPartion">
		<property name="splitOneDay">24</property>
	</function>

	<!--按照月分片-->
	<function name="partbymonth"
		class="io.mycat.route.function.PartitionByMonth">
		<property name="dateFormat">yyyy-MM-dd</property>
		<property name="sBeginDate">2018-01-01</property>
	</function>
	
	<function name="rang-mod" class="io.mycat.route.function.PartitionByRangeMod">
        	<property name="mapFile">partition-range-mod.txt</property>
	</function>
	
	<function name="jump-consistent-hash" class="io.mycat.route.function.PartitionByJumpConsistentHash">
		<property name="totalBuckets">3</property>
	</function>
</mycat:rule>

=== MyCATApache/Mycat-Server/src/test/resources/route/disRoute/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - Licensed under the Apache License, Version 2.0 (the "License"); 
	- you may not use this file except in compliance with the License. - You 
	may obtain a copy of the License at - - http://www.apache.org/licenses/LICENSE-2.0 
	- - Unless required by applicable law or agreed to in writing, software - 
	distributed under the License is distributed on an "AS IS" BASIS, - WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. - See the 
	License for the specific language governing permissions and - limitations 
	under the License. -->
<!DOCTYPE mycat:rule SYSTEM "rule.dtd">
<mycat:rule xmlns:mycat="http://io.mycat/">


    <tableRule name="sharding-by-id">
        <rule>
            <columns>ID</columns>
            <algorithm>mod-long</algorithm>
        </rule>
    </tableRule>
    <function name="partbymonth"
        class="io.mycat.route.function.PartitionByMonth">
        <property name="dateFormat">yyyy-MM-dd</property>
        <property name="sBeginDate">2017-01-01</property>
    </function>
    <function name="mod-long" class="io.mycat.route.function.PartitionByMod">
        <!-- how many data nodes -->
        <property name="count">2</property>
    </function>
</mycat:rule>

=== MyCATApache/Mycat-Server/src/test/resources/route/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - Licensed under the Apache License, Version 2.0 (the "License"); 
	- you may not use this file except in compliance with the License. - You 
	may obtain a copy of the License at - - http://www.apache.org/licenses/LICENSE-2.0 
	- - Unless required by applicable law or agreed to in writing, software - 
	distributed under the License is distributed on an "AS IS" BASIS, - WITHOUT 
	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. - See the 
	License for the specific language governing permissions and - limitations 
	under the License. -->
<!DOCTYPE mycat:rule SYSTEM "rule.dtd">
<mycat:rule xmlns:mycat="http://io.mycat/">

	<tableRule name="offerRule">
		<rule>
			<columns>member_id</columns>
			<algorithm>func</algorithm>
		</rule>
	</tableRule>
	
	<tableRule name="dateRule">
		<rule>
			<columns>col_date</columns>
			<algorithm>by-date</algorithm>
		</rule>
	</tableRule>

	<tableRule name="offerDetailRule">
		<rule>
			<columns>offer_id</columns>
			<algorithm>func2</algorithm>
		</rule>
	</tableRule>
	<tableRule name="sharding-by-intfile">
		<rule>
			<columns>sharding_id</columns>
			<algorithm>func1</algorithm>
		</rule>
	</tableRule>
	<tableRule name="auto-sharding-long">
		<rule>
			<columns>id</columns>
			<algorithm>rang-long</algorithm>
		</rule>
	</tableRule>
	<tableRule name="auto-sharding-long2">
		<rule>
			<columns>id</columns>
			<algorithm>rang-long2</algorithm>
		</rule>
	</tableRule>

    <tableRule name="auto-sharding-rang-mod">
        <rule>
            <columns>id</columns>
            <algorithm>rang-mod</algorithm>
        </rule>
    </tableRule>
    
    <tableRule name="partitionByMod">
    	<rule>
    		<columns>id</columns>
    		<algorithm>partitionByMod</algorithm>
    	</rule>
    </tableRule>
    
    <tableRule name="rangeDateHash">
        <rule>
            <columns>col_date</columns>
            <algorithm>range-date-hash</algorithm>
        </rule>
    </tableRule>
	<tableRule name="crc32slot">
		<rule>
			<columns>id</columns>
			<algorithm>crc32slot</algorithm>
		</rule>
	</tableRule>
	
	<tableRule name="mod-long">
		<rule>
			<columns>id</columns>
			<algorithm>mod-long</algorithm>
		</rule>
	</tableRule>
	
	<function name="partitionByMod" class="io.mycat.route.function.PartitionByMod">
		<property name="count">2</property>
	</function>
	<function name="func1"
		class="io.mycat.route.function.PartitionByFileMap">
		<property name="defaultNode">0</property>
		<property name="mapFile">sharding.txt</property>
	</function>
	<function name="func"
		class="io.mycat.route.function.PartitionByString">
		<property name="partitionCount">128</property>
		<property name="partitionLength">8</property>
		<property name="hashSlice">:8</property>
	</function>
	<function name="func2" class="io.mycat.route.function.PartitionByLong">
		<property name="partitionCount">128</property>
		<property name="partitionLength">8</property>
	</function>
	<function name="rang-long"
		class="io.mycat.route.function.AutoPartitionByLong">
		<property name="mapFile">autopartition-long.txt</property>
	</function>
	<function name="rang-long2"
		class="io.mycat.route.function.AutoPartitionByLong">
		<property name="mapFile">autopartition-long2.txt</property>
	</function>
	<function name="by-date"
		class="io.mycat.route.function.PartitionByDate">                            
		<property name="sBeginDate">2014-01-01</property>
		<property name="sPartionDay">10</property>
		<property name="dateFormat">yyyy-MM-dd</property>
	</function>

    <function name="rang-mod"
              class="io.mycat.route.function.PartitionByRangeMod">
        <property name="mapFile">partition-range-mod.txt</property>
    </function>

    <function name="range-date-hash"
              class="io.mycat.route.function.PartitionByRangeDateHash">
        <property name="sBeginDate">2014-01-01 00:00:00</property>
        <property name="sPartionDay">3</property>
        <property name="dateFormat">yyyy-MM-dd HH:mm:ss</property>
        <property name="groupPartionSize">6</property>
    </function>

	<function name="crc32slot"
			  class="io.mycat.route.function.PartitionByCRC32PreSlot">
	</function>
	
	<function name="mod-long" class="io.mycat.route.function.PartitionByMod">
			<!-- how many data nodes -->
			<property name="count">2</property>
	</function>
</mycat:rule>
